# Generated by Django 3.2.7 on 2021-09-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210918_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='', max_length=300),
        ),
    ]
