# Generated by Django 3.2.7 on 2021-10-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
    ]
