# Generated by Django 3.2.7 on 2021-10-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
