# Generated by Django 3.2.7 on 2021-10-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='web_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='writer',
            field=models.BooleanField(default=False),
        ),
    ]
